# Generated by Django 5.2.11 on 2026-03-08 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('PHISHING', 'Phishing'), ('VISHING', 'Vishing'), ('SMISHING', 'Smishing')], max_length=20)),
                ('portal_type', models.CharField(choices=[('PUBLIC', 'Public Portal'), ('EMPLOYEE', 'Employee Portal')], max_length=20)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], max_length=2)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('current_scene', models.IntegerField(default=0)),
                ('total_scenes', models.IntegerField(default=0)),
                ('quiz_score', models.IntegerField(blank=True, null=True)),
                ('quiz_total', models.IntegerField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('quiz_answers', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interactive Lesson Progress',
                'verbose_name_plural': 'Interactive Lesson Progress',
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'lesson_type', 'portal_type', 'language')},
            },
        ),
    ]
